import React from 'react'
import FAQ from './FAQ';

export const metadata = {
  title: "Frequently Asked Questions",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
        <FAQ/>
    </>
  )
}