import React from 'react'
import PageNotFound from './Components/PageNotFound';
import './assets/css/style.css'
import Mainlayout from './Components/Common/Mainlayout';

export const metadata = {
  title: "Page Not Found",
  description: "Generated by create next app",
};

export default function notFound() {
  return (
    <>
    <Mainlayout>
      <PageNotFound/>
    </Mainlayout>
    </>
  )
}
