
import React from 'react'
import Login from './Login'

export const metadata = {
  title: "My Account Login register",
  description: "Generated by create next app",
};

export default function page() {

  return (
    <>
      <Login/>
    </>
  )
}
