import React from 'react'
import Reset from './Reset';

export const metadata = {
    title: "Reset Password",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <>
            <Reset/>
        </>
    )
}
