import '../assets/css/style.css'
import Mainlayout from '../Components/Common/Mainlayout';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="min-h-full flex flex-col">
        <Mainlayout>
          {children}
        </Mainlayout>
      </body>
    </html>
  );
}
