import Image from "next/image";
import HomePage from "../Components/HomePage";
import { menProducts, womenProducts } from "./ApiServies/ApiServices";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function Home() {


  const mens = await menProducts();
  const womens = await womenProducts();

  return (
    <>
      <HomePage men={mens} women={womens}/>
    </>
  );
}
