import React from 'react'
import Cart from './Cart';

export const metadata = {
  title: "Shopping Cart",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
        <Cart/>
    </>
  )
}
