import React from 'react'
import Privacy from './Privacy'


export const metadata = {
  title: "Privacy Policy",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <Privacy/>
    </>
  )
}
