import Header from "@/Components/Common/Header";
import "../app/css/style.css";
import Footer from "@/Components/Common/Footer";
import Commonlayout from "@/Components/Common/Commonlayout";

export const metadata = {
  title: "Online Furniture In India",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Commonlayout>
          <Header/>
            {children}
          <Footer/>
        </Commonlayout>
      </body>
    </html>
  );
}
