import React from 'react'
import Checkout from './Checkout';

export const metadata = {
    title: "Checkout",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <>
            <Checkout/>
        </>
    )
}
