import React from 'react'
import ContactUs from './ContactUs';

export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
        <ContactUs/>
    </>
  )
}
