import React from 'react'
import SideAndEndTables from './SideAndEndTables'

export const metadata = {
  title: "Product Listing",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <SideAndEndTables/>
    </>
  )
}
