import './assets/css/style.css'
import ComoonLayout from './Components/Common/ComoonLayout';

export const metadata = {
  title: "Next Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">

        <ComoonLayout>
          {children}
        </ComoonLayout>

      </body>
    </html>
  );
}
