import Home from "./Components/Home";

export const metadata = {
  title: "Home Page | Next Application",
  description: "Generated by create next app",
};

export default function HomePage() {

  console.log(process.env.NEXT_PUBLIC_API_URL)

  return (
    <Home/>
  );
}
