import React from 'react'
import Forgot from './Forgot';

export const metadata = {
    title: "Forgot Password",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <>
            <Forgot/>
        </>
    )
}
