import React from 'react'

export const metadata = {
  title: "About Us Page | Next Application",
  description: "Generated by create next app",
};

export default function page() {

  
  return (
    <div className='text-center'>
      About Us
    </div>
  )
}
