import React from 'react'
import About from './About';

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
        <About/>
    </>
  )
}